# Generated by Django 4.1.1 on 2022-10-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStock',
            new_name='count_in_stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
